### ISSUE TITLE
Setup recommendations counts advanced options even when disabled.

### ISSUE THREAD

**Issue by skunk-ink** [SiaFoundation/desktop#90]
When using the configuration page with `Advanced settings` deactivated, the recommendations pop-up suggests users can configure 75 options. In reality, with `Advanced settings` toggled off, only 7 settings can be configured. This could potentially cause some confusion for users. I suggest the counter should change to reflect the number of options available depending on if `Advanced settings` is toggled on or off.

![Screenshot from 2024-08-19 00-13-04](https://github.com/user-attachments/assets/6c81c0a0-4a54-4c61-9170-d6254febe750)

**Comment by alexfreska** [comment]
@skunk-ink the 0/75 mean the current settings match with 0 hosts and the ideal number is 75, the tooltip breaks this down more clearly. Sounds like this is a bit confusing, I can look at making it more clear.
<img width="721" alt="Screenshot 2024-08-19 at 8 34 31 AM" src="https://github.com/user-attachments/assets/cd721592-b417-4f5a-82d0-517d11407b8a">

**Comment by skunk-ink** [comment]
Ahh, yeah, that makes more sense, haha. I think the 0/75 and 0 matching is what made it a bit confusing. It makes more sense when there is more context to it, like in your screenshot or when I look at my personal `renterd`. What about adding something like a mouse over tool tip to elaborate on the meaning?

**Comment by skunk-ink** [comment]
Oh, whoops! I never even thought of seeing if there was a mouse-over tooltip. My bad 😅. It makes more intuitive sense when there is more context, like in your screenshot or my personal `renterd` and I think the 0/75 and 0 matchings are what made it a bit confusing. As in my screenshot, it can be read as the two numbers being related. Maybe remove the `0` and just say, "No recommendations."?
